### ISSUE TITLE
Create documentation for buildout.org hosted by GitHub or RTD

### ISSUE THREAD

**Issue by aclark4life** [buildout/buildout.github.com#1]
```
19:33 < J1m> To move to GH, someone needs to write up a how-to 
for how we update the docs that involves updating sphinx sources, 
building and pushing.
```

**Comment by reinout** [comment]
I'm sure I've asked it before, but can't find it: where is it hosted now and how is the documentation updated?

Moving to a standard readthedocs layout without too much extra graphics might be best.

**Comment by jimfulton** [comment]
It's hosted on RTD. I believe all you have to do is check changes in here.

The RTD project is owned by Alex and Hanno.

RTD says it was last built 2 days ago.
